packages:
  - apps/*
  - packages/*
  - packages/design-system/*
  - tooling/*

catalog:
  "@cloudflare/workers-types": 4.20260426.1
  "@t3-oss/env-nextjs": ^0.13.11
  "@types/node": ^24.12.2
  "@types/react": ^19.2.14
  "@types/react-dom": ^19.2.3
  eslint: ^9.39.4
  tailwindcss: ^4.2.4
  tsdown: ^0.21.10
  typescript: ^5.9.3
  server-only: ^0.0.1
  "@orpc/client": 1.14.0
  "@orpc/server": 1.14.0
  "@orpc/tanstack-query": 1.14.0
  "@orpc/openapi": 1.14.0
  "@orpc/zod": 1.14.0
  "@polar-sh/better-auth": 1.8.3
  "@sentry/nextjs": 10.50.0
  better-auth: 1.6.9
  drizzle-orm: 0.45.2
  next: 16.2.4
  react: 19.2.5
  react-dom: 19.2.5
  wrangler: 4.85.0
  zod: 4.3.6

onlyBuiltDependencies:
  - "@sentry/cli"
  - core-js
  - esbuild
  - lefthook
  - protobufjs
  - rclone.js
  - sharp
  - unrs-resolver
  - workerd
