packages:
  - apps/*
  - packages/*
  - packages/design-system/*
  - quark/*

catalog:
  "@cloudflare/workers-types": 4.20251218.0
  "@orpc/client": 1.13.0
  "@orpc/server": 1.13.0
  "@orpc/tanstack-query": 1.13.0
  "@polar-sh/better-auth": 1.6.3
  "@sentry/nextjs": 10.32.1
  "@t3-oss/env-nextjs": 0.13.10
  "@types/node": 24.10.4
  "@types/react": 19.2.7
  "@types/react-dom": 19.2.3
  better-auth: 1.4.7
  drizzle-orm: 0.45.1
  eslint: 9.39.2
  next: 16.1.0
  react: 19.2.3
  react-dom: 19.2.3
  server-only: 0.0.1
  tailwindcss: 4.1.18
  tsdown: 0.18.1
  typescript: 5.9.3
  wrangler: 4.56.0
  zod: 4.2.1

onlyBuiltDependencies:
  - "@sentry/cli"
  - core-js
  - esbuild
  - lefthook
  - protobufjs
  - rclone.js
  - sharp
  - unrs-resolver
  - workerd
